### ISSUE TITLE
Returns empty string

### ISSUE THREAD

**Issue by grepinsight** [arunsupe/semantic-grep#11]
Hi. I pulled `99ece7a` and tried to test this tool.

Currently it returns nothing using the example in the README.txt.

```
curl 'https://gutenberg.ca/ebooks/hemingwaye-oldmanandthesea/hemingwaye-oldmanandthesea-00-t.txt' \
    | sgrep -C 2 -n -threshold 0.55 -model_path models/glove/glove.6B.300d.bin death
```

Also tried

```
curl 'https://gutenberg.ca/ebooks/hemingwaye-oldmanandthesea/hemingwaye-oldmanandthesea-00-t.txt' \
    | sgrep -C 2 -n -threshold 0.55 -model_path models/googlenews-slim/GoogleNews-vectors-negative300-SLIM.bin death
```

**Comment by arunsupe** [comment]
I bet this is due to git-lfs not installed or configured correctly. In which case, you have 2 options:

1. Just download the model directly using the browser from [models/glove/glove.6B.300d.bin](https://github.com/arunsupe/semantic-grep/raw/main/models/glove/glove.6B.300d.bin?download=) and point the -model_path to the downloaded file's location

2. Install git lfs
```text
  To properly download and manage LFS-tracked files, you need to:
  
  Install Git LFS for your platform: This sets up the necessary tools to handle LFS files.   
  Run git lfs install: This configures Git to use LFS for the repository.   
  Clone the repository: Now, when you clone the repository, Git LFS will automatically download the actual files instead of the placeholders.
```

If LFS is not the issue, could you please do the following:
1. double-check model exists in model_path (git leaves a text stub if LFS is not installed)
2. model_path is correct
3. the binary is correctly compiled

I will leave this issue open for 24 hours so you can respond here if you are still having difficulty.

**Comment by arunsupe** [comment]
Haven't heard back. Assuming the best :-)
