### ISSUE TITLE
Error loading full model: unsupported file format

### ISSUE THREAD

**Issue by coljac** [arunsupe/semantic-grep#12]
- I cloned the repo and built.
- I ran the download script.
- I updated the config.json to point to the downloaded model file, `models/googlenews-slim/GoogleNews-vectors-negative300-SLIM.bin`

The result was 

```
Using configuration file: /home/coljac/Downloads/semantic-grep/config.json
Error loading full model: unsupported file format

```

The config is just

```
{
    "model_path": "/home/coljac/Downloads/semantic-grep/models/googlenews-slim/GoogleNews-vectors-negative300-SLIM.bin"
}
```

**Comment by arunsupe** [comment]
For the model to download with `git clone`, git-lfs should be installed (because the models are large). Try downloading the model directly as a raw file from models/googlenews-slim/GoogleNews-vectors-negative300-SLIM.bin using the browser (https://github.com/arunsupe/semantic-grep/raw/main/models/googlenews-slim/GoogleNews-vectors-negative300-SLIM.bin?download=) and placing in models/googlenews-slim/GoogleNews-vectors-negative300-SLIM.bin

**Comment by coljac** [comment]
Apologies - I know not what I changed, but I got it to work. Close this one!

**Comment by kenorb** [comment]
```
sudo apt install git-lfs
git lfs install
git lfs fetch
git lfs checkout
```
