### ISSUE TITLE
Add SIMD support for faster multiplication

### ISSUE THREAD

**Issue by brunodoamaral** [arunsupe/semantic-grep#6]
Hi! First, thanks for sharing your code.

I have one suggestion that is to use SIMD operation to accelerate vector multiplications.

I’m not familiar with the Go ecosystem, but this lib seems to do the job: https://github.com/viterin/vek

Here is the code to be optimized:

https://github.com/arunsupe/semantic-grep/blob/b7dcc82a7cbab4fc4fdc1d4ef86092a071e48455/sgrep.go#L115-L125

That can simply be replaced by

```go
func calculateSimilarity(vec1, vec2 []float32) float64 {
    return vek.CosineSimilarity(vec1, vec2)
}
```

**Comment by arunsupe** [comment]
Thank you for the suggestion. I tested this. It works exactly as you say - a very simple drop-in replacement as you have indicated. (Also had to change the vector size from 32 to 64 bit)

However, I'm not seeing any performance improvement in the very quick testing I have done. Not sure if this because the bottleneck is the large model loading overhead. 

I'm going close this issue. However I will test more.
